name: drought
channels:
  - conda-forge
  - base
  - bioconda
  - R
dependencies:
  - r-base=4.1.3
  - r-tidyverse=1.3.2
  - r-rmarkdown=2.18
  - r-showtext=0.9
  - r-maps>=3.4
  - wget=1.20.3
  - snakemake=7.18.2
  - graphviz=6.0.1
  - coreutils>=9.1
